### ISSUE TITLE
Unable to import raster foundry python client in fresh install

### ISSUE THREAD

**Issue by CloudNiner** [raster-foundry/raster-foundry-python-client#55]
This worked _very_ recently, as early as this morning I believe.

But now, I cannot install and import the `rasterfoundry.api.API` class in my python interpreter:
```
mkvirtualenv rf-api-test
pip3 install rasterfoundry ipython

# then 
(rf-api-test) andrew@shenandoah ~/src/prediction-api: python3
Python 3.6.5 (default, Apr 25 2018, 14:23:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from rasterfoundry.api import API
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/rasterfoundry/api.py", line 11, in <module>
    from .aws.s3 import str_to_file
  File "/usr/local/lib/python3.6/site-packages/rasterfoundry/aws/s3.py", line 14, in <module>
    s3 = boto3.client('s3')
  File "/usr/local/lib/python3.6/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 861, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 76, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 285, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.6/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python3.6/site-packages/botocore/args.py", line 111, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 361, in resolve
    resolved, service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 378, in _create_endpoint
    if self._is_s3_dualstack_mode(service_name):
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 410, in _is_s3_dualstack_mode
    enabled = self.scoped_config.get('s3', {}).get(
AttributeError: 'str' object has no attribute 'get'
```

**Comment by CloudNiner** [comment]
Output of `pip3 freeze`:
```
appnope==0.1.0
asn1crypto==0.24.0
backcall==0.1.0
boto3==1.7.40
botocore==1.10.40
bravado==10.0.0
bravado-core==5.0.3
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
cryptography==2.2.2
decorator==4.3.0
docutils==0.14
future==0.16.0
idna==2.7
ipython==6.4.0
ipython-genutils==0.2.0
jedi==0.12.0
jmespath==0.9.3
jsonref==0.1
jsonschema==2.6.0
monotonic==1.5
msgpack-python==0.5.6
parso==0.2.1
pexpect==4.6.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
pyasn1==0.4.3
pycparser==2.18
Pygments==2.2.0
python-dateutil==2.7.3
pytz==2018.4
PyYAML==3.12
rasterfoundry==0.6.0
requests==2.19.1
rfc3987==1.3.7
s3transfer==0.1.13
Shapely==1.6.4.post1
simplegeneric==0.8.1
simplejson==3.15.0
six==1.11.0
strict-rfc3339==0.7
swagger-spec-validator==2.3.1
traitlets==4.3.2
urllib3==1.23
wcwidth==0.1.7
webcolors==1.8.1
```
